apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fusion-spectra
  namespace: fusion
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: spectra.fusion.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fusion-spectra
                port:
                  number: 80
