{{- if .Values.plugins.forgePlugin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-forge-plugin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-spectra.labels" . | nindent 4 }}
    app: fusion-forge-plugin
    app.kubernetes.io/component: plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-forge-plugin
  template:
    metadata:
      labels:
        app: fusion-forge-plugin
        {{- include "fusion-spectra.labels" . | nindent 8 }}
    spec:
      containers:
        - name: plugin
          image: "{{ .Values.plugins.forgePlugin.image.repository }}:{{ .Values.plugins.forgePlugin.image.tag }}"
          imagePullPolicy: {{ .Values.plugins.forgePlugin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.plugins.forgePlugin.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
{{- end }}
