apiVersion: v1
kind: Service
metadata:
  name: fusion-spectra
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fusion-spectra.labels" . | nindent 4 }}
    app: fusion-spectra
spec:
  type: ClusterIP
  selector:
    app: fusion-spectra
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
