<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import CanvasPanel from '@/components/CanvasPanel.vue'
import { usePermission } from '@/composables/usePermission'

const router = useRouter()
const { can } = usePermission()

interface WizardCard {
  id:    string
  title: string
  icon:  string
  desc:  string
  route: string
}

const wizards = computed<WizardCard[]>(() => {
  const cards: WizardCard[] = [
    {
      id:    'git-python-job',
      title: 'Git → Python Job',
      icon:  'mdi-language-python',
      desc:  'Point at a git repo with several Python scripts — get a GitOps-built artifact, a run blueprint, and one trigger per entrypoint, wired up automatically.',
      route: '/wizards/run/python-git-job/create',
    },
    {
      id:    'git-batch-job',
      title: 'Git → Batch Job',
      icon:  'mdi-tray-full',
      desc:  'Point at a git repo/branch/subfolder containing a single batch job — get a GitOps-built artifact, a run blueprint and trigger, and the first run fired immediately.',
      route: '/wizards/run/batch-git-job/create',
    },
  ]
  if (can('weave:batchtriggers:write')) {
    cards.push({
      id:    'git-batchcron-job',
      title: 'Git → BatchCron Job',
      icon:  'mdi-calendar-multiple',
      desc:  'Point at a git repo/branch/subfolder, then paste an autogenerated list of many cron-scheduled jobs — get a GitOps-built artifact, a run blueprint, and a BatchCron trigger running every entry on its own schedule.',
      route: '/wizards/run/batchcron-git-job/create',
    })
  }
  return cards
})
</script>

<template>
  <div class="page-grid">
    <CanvasPanel title="Wizards" icon="mdi-creation" :wide="true">
      <template #actions>
        <button class="fs-btn fs-btn--ghost" @click="router.push('/wizards/runs')">
          <q-icon name="mdi-history" size="14px" /> View Runs
        </button>
      </template>
      <div class="wizard-grid">
        <button
          v-for="w in wizards"
          :key="w.id"
          class="wizard-card"
          @click="router.push(w.route)"
        >
          <q-icon :name="w.icon" size="26px" class="wizard-card__icon" />
          <span class="wizard-card__title">{{ w.title }}</span>
          <span class="wizard-card__desc">{{ w.desc }}</span>
        </button>
      </div>
    </CanvasPanel>
  </div>
</template>

<style scoped>
.page-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 14px;
  padding: 16px;
  align-content: start;
}

.wizard-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
  gap: 12px;
  padding: 4px 10px 10px;
}

.wizard-card {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 8px;
  padding: 16px;
  text-align: left;
  border: 1px solid var(--fs-border);
  border-radius: 6px;
  background: var(--fs-bg-elevated);
  cursor: pointer;
  font-family: inherit;
  transition: border-color var(--fs-ease), background var(--fs-ease);
}
.wizard-card:hover { border-color: var(--fs-accent); background: var(--fs-bg-hover); }
.wizard-card__icon  { color: var(--fs-accent); }
.wizard-card__title { font-size: 13.5px; font-weight: 600; color: var(--fs-text-primary); }
.wizard-card__desc  { font-size: 11.5px; color: var(--fs-text-muted); line-height: 1.5; }

.fs-btn {
  display: inline-flex; align-items: center; gap: 6px; padding: 7px 16px;
  border-radius: 4px; font-size: 12.5px; font-family: inherit; font-weight: 500;
  cursor: pointer; border: 1px solid transparent;
  transition: background var(--fs-ease), border-color var(--fs-ease), color var(--fs-ease);
}
.fs-btn--ghost { background: transparent; color: var(--fs-text-muted); border-color: var(--fs-border); }
.fs-btn--ghost:hover { color: var(--fs-text-primary); background: var(--fs-bg-hover); }
</style>
